// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzopcuobfictkngqcffb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6b3BjdW9iZmljdGtuZ3FjZmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDI3NDIsImV4cCI6MjA2MzMxODc0Mn0.7gifgfQBovWjhs4pLPCTE3b0uF2VEAjqjtKg_OHMjqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);